name: CI · Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.sln','**/*.csproj') }}
          restore-keys: nuget-${{ runner.os }}-

      - name: Restore packages
        run: nuget restore WindowServiceApp.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: msbuild WindowServiceApp.sln /m /p:Configuration=Release

      - name: Run xUnit tests
        run: dotnet test WindowServiceApp.sln --configuration Release --no-build
